[package]
name = "proc"
version = "0.1.103"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
macros = { workspace = true }
quote = "1.0.37"
syn = { version = "2.0.90", features = ["default", "full"] }
convert_case = "0.10"
proc-macro2 = "1.0.92"