[package]
name = "proc"
version = "0.1.103"
edition = "2021"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
macros = { workspace = true }
quote = "1.0.44"
syn = { version = "2.0.114", features = ["default", "full"] }
convert_case = "0.11.0"
proc-macro2 = "1.0.106"